const $ = id => document.getElementById(id);
const key = '考研资料管家.v1';
const aiKey = '考研资料管家.ai';
const esc = v => String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safeId = v => String(v || '').replace(/[^A-Za-z0-9_-]/g, '');
let data = {items:[],progress:'',review:'',log:[]};
let ai = {baseUrl:'https://api.deepseek.com',model:'deepseek-v4-flash',apiKey:''};
try { data = {...data, ...JSON.parse(localStorage.getItem(key) || '{"items":[],"progress":"","review":"","log":[]}')}; } catch(e) { data = {items:[],progress:'',review:'',log:[]}; }
try { ai = {...ai, ...JSON.parse(localStorage.getItem(aiKey) || '{}')}; } catch(e) { ai = {baseUrl:'https://api.deepseek.com',model:'deepseek-v4-flash',apiKey:''}; }
const selected = new Set();

function mkId(){return `${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`}
function normalizeItem(x){let tags=Array.isArray(x.tags)?x.tags:typeof x.tags==='string'?parseTags(x.tags):[];return {...x,id:x.id||mkId(),tags:parseTags(tags.join(',')),updatedAt:x.updatedAt||new Date().toISOString()}}
data.items=data.items.map(normalizeItem);

function persist(){try{data.log=data.log.slice(0,200);localStorage.setItem(key,JSON.stringify(data));}catch(err){alert('保存失败：本地存储空间不足。请先导出同步包，并在导入端合并。')}render()}
function show(id){document.querySelectorAll('section').forEach(x=>x.hidden=x.id!==id)}
function loadAI(){aiBase.value=ai.baseUrl;aiModel.value=ai.model;aiApiKey.value=ai.apiKey}
function saveAI(){ai.baseUrl=aiBase.value.trim()||'https://api.deepseek.com';ai.model=aiModel.value.trim()||'deepseek-v4-flash';ai.apiKey=aiApiKey.value.trim();localStorage.setItem(aiKey,JSON.stringify(ai));alert('AI 配置已保存到本机')}
function parseTags(v){return [...new Set((v||'').split(/[,\n，、\s]+/).map(x=>x.trim()).filter(Boolean))]}
function matches(item,q){if(!q)return true;return [item.name,item.subject,item.type,item.level,item.status,item.time,...(item.tags||[]),...(item.attachments||[]).map(a=>a.name)].join(' ').toLowerCase().includes(q)}
function renderStats(items){let c=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,v])=>`${esc(k)}(${v})`).join(' · ')||'无';let s={},l={},t={};items.forEach(x=>{s[x.subject]=(s[x.subject]||0)+1;(x.level||'未设层级')&&(l[x.level||'未设层级']=(l[x.level||'未设层级']||0)+1);(x.tags||[]).forEach(k=>t[k]=(t[k]||0)+1)});stats.textContent=`共 ${items.length} 条｜已选 ${selected.size} 条｜科目 ${c(s)}｜层级 ${c(l)}｜标签 ${c(t)}`}
function renderTree(items){let treeData={};items.forEach(x=>{let s=treeData[x.subject]||(treeData[x.subject]={count:0,types:{}});s.count++;let t=s.types[x.type||'未分类']||(s.types[x.type||'未分类']={count:0,levels:{}});t.count++;let lv=x.level||'未设层级';t.levels[lv]=(t.levels[lv]||0)+1});let html=Object.entries(treeData).map(([subject,s])=>`<details class="tree-group" open><summary>${esc(subject)} (${s.count})</summary>${Object.entries(s.types).map(([type,t])=>`<div class="tree-node"><details><summary>${esc(type)} (${t.count})</summary>${Object.entries(t.levels).map(([lv,n])=>`<div class="tree-leaf">${esc(lv)} (${n})</div>`).join('')}</details></div>`).join('')}</details>`).join('');tree.innerHTML=html||'<p class="muted">暂无资料</p>'}
function add(){let n=name.value.trim();if(!n)return alert('请填写资料名称');let fileInput=$('files'),fs=[...fileInput.files].map(f=>({name:f.name,size:f.size,type:f.type||'unknown'})),lv=$('level').value.trim(),tg=parseTags($('tags').value);data.items.unshift(normalizeItem({id:mkId(),name:n,subject:subject.value,type:type.value||'未分类',level:lv,tags:tg,attachments:fs,time:new Date().toLocaleString(),status:'未整理'}));data.log.unshift(`${new Date().toLocaleString()}：新增资料「${n}」${lv?'；层级：'+lv:''}${tg.length?'；标签：'+tg.join('、'):''}；下一步：同步到 Windows 后归档`);name.value='';type.value='';$('level').value='';$('tags').value='';fileInput.value='';persist()}
function render(){let q=$('filter').value.trim().toLowerCase(),rows=data.items.map((x,i)=>({x,i})).filter(o=>matches(o.x,q));list.innerHTML=rows.map(({x,i})=>`<div class="item"><label><input type="checkbox" ${selected.has(x.id)?'checked':''} onchange="togglePick('${safeId(x.id)}',this.checked)"> <b>${esc(x.name)}</b></label><br><span class="muted">${esc(x.subject)} · ${esc(x.type)} · ${esc(x.level||'未设层级')} · ${esc(x.status)} · ${esc(x.time)}${x.tags&&x.tags.length?' · 标签：'+x.tags.map(esc).join('、'):''}${x.attachments&&x.attachments.length?' · 附件：'+x.attachments.map(a=>esc(a.name)).join('、'):''}</span><br><button onclick="editClass(${i})">改归类</button> <button onclick="done(${i})">标记已整理</button></div>`).join('')||'<p class="muted">暂无资料，先把资料加入收件箱。</p>';progress.value=data.progress;review.value=data.review;renderStats(rows.map(o=>o.x));renderTree(data.items)}
function togglePick(id,on){on?selected.add(id):selected.delete(id);render()}
function selectVisible(on){let rows=data.items.filter(x=>matches(x,$('filter').value.trim().toLowerCase()));rows.forEach(x=>on?selected.add(x.id):selected.delete(x.id));render()}
function clearSelection(){selected.clear();render()}
function batchEditLevel(){let items=data.items.filter(x=>selected.has(x.id));if(!items.length)return alert('先勾选要修改的资料');let levelValue=prompt('批量修改层级（留空会清空）',items[0].level||'');if(levelValue===null)return;items.forEach(x=>x.level=levelValue.trim());data.log.unshift(`${new Date().toLocaleString()}：批量调整 ${items.length} 条资料层级；下一步：核对目录结构`);selected.clear();persist()}
function batchEditTags(){let items=data.items.filter(x=>selected.has(x.id));if(!items.length)return alert('先勾选要修改的资料');let current=[...new Set(items.flatMap(x=>x.tags||[]))].join(',');let tagsValue=prompt('批量修改标签（逗号分隔）',current);if(tagsValue===null)return;let tags=parseTags(tagsValue);if(!tags.length)return alert('请至少输入一个标签');let replace=confirm('确定覆盖原标签吗？取消=追加到原标签');items.forEach(x=>x.tags=replace?tags:[...new Set([...(x.tags||[]),...tags])]);data.log.unshift(`${new Date().toLocaleString()}：批量调整 ${items.length} 条资料标签；下一步：核对标签和目录是否一致`);selected.clear();persist()}
function done(i){data.items[i].status='已整理';data.log.unshift(`${new Date().toLocaleString()}：资料「${data.items[i].name}」标记为已整理；下一步：按科目归档`);persist()}
function editClass(i){let x=data.items[i],subjectValue=prompt('修改所属科目',x.subject);if(subjectValue===null)return;let typeValue=prompt('修改模块/类型',x.type||'未分类');if(typeValue===null)return;let levelValue=prompt('修改层级（例如：英语/阅读/细节题）',x.level||'');if(levelValue===null)return;let tagsValue=prompt('修改标签（逗号分隔）',(x.tags||[]).join(','));if(tagsValue===null)return;x.subject=subjectValue.trim()||x.subject;x.type=typeValue.trim()||'未分类';x.level=levelValue.trim();x.tags=parseTags(tagsValue);data.log.unshift(`${new Date().toLocaleString()}：资料「${x.name}」已调整归类；下一步：检查目录和标签是否一致`);persist()}
function save(k){data[k]=$(k).value;data.log.unshift(`${new Date().toLocaleString()}：更新${k==='progress'?'学习进度':'复盘'}；下一步：继续补充并完成同步`);persist();alert('已保存到本机')}
function sync(){let blob=new Blob([JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='考研资料管家同步包.json';a.click();data.log.unshift(`${new Date().toLocaleString()}：生成同步包；下一步：将 JSON 文件发送到 Windows 或云盘`);persist()}
function exportClassList(){let lines=['# 考研资料分类清单',''];data.items.forEach((x,i)=>{lines.push(`- ${i+1}. ${x.name}`);lines.push(`  - 科目：${x.subject}`);lines.push(`  - 模块：${x.type}`);lines.push(`  - 层级：${x.level||'未设层级'}`);lines.push(`  - 标签：${x.tags&&x.tags.length?x.tags.join('、'):'无标签'}`);lines.push(`  - 状态：${x.status}`);if(x.attachments&&x.attachments.length)lines.push(`  - 附件：${x.attachments.map(a=>a.name).join('、')}`);});let blob=new Blob([lines.join('\n')],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='考研资料分类清单.md';a.click();data.log.unshift(`${new Date().toLocaleString()}：导出分类清单；下一步：核对层级、标签和目录是否一致`);persist()}
function importPack(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.items))throw new Error('no items');
// 导入前自动备份本机数据
let backupBlob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),ba=document.createElement('a');ba.href=URL.createObjectURL(backupBlob);ba.download=`导入前备份-${new Date().toISOString().slice(0,10)}.json`;ba.click();
// 按 id 合并；同 id 冲突时以 updatedAt 较新者为主，旧版本重命名保留为冲突副本
let byId=new Map(data.items.map(i=>[i.id,i]));let updated=0,conflicted=0;(x.items||[]).forEach(incoming=>{let inc=normalizeItem(incoming);let local=byId.get(inc.id);if(!local){byId.set(inc.id,inc);updated++;return;}let incTime=Date.parse(inc.updatedAt||0)||0,locTime=Date.parse(local.updatedAt||0)||0;if(incTime>=locTime){byId.set(inc.id,inc);updated++;}else{if(!local.name.endsWith('(旧版)')){let dup={...local,name:`${local.name}(旧版)`,id:`${local.id}-old-${Date.now().toString(36)}`};byId.set(dup.id,dup);}conflicted++;}});data.items=[...byId.values()].map(normalizeItem);data.progress=x.progress||data.progress;data.review=x.review||data.review;data.log=[...(x.log||[]),`${new Date().toLocaleString()}：导入同步包（新增 ${updated} 条，冲突保留 ${conflicted} 条）；导入前备份已下载；下一步：检查新增资料并归档`].slice(0,200);selected.clear();persist();alert(`同步包已导入：新增 ${updated} 条${conflicted?`，冲突保留 ${conflicted} 条`:''}`)}catch(err){alert('同步包格式无效')}};r.readAsText(f)}
function contextText(){return data.items.length?data.items.map((x,i)=>`${i+1}. ${x.name}｜${x.subject}｜${x.type}｜${x.level||'未设层级'}｜${x.tags&&x.tags.length?x.tags.join('、'):'无标签'}｜${x.status}${x.attachments&&x.attachments.length?'｜附件:'+x.attachments.map(a=>a.name).join('、'):''}`).join('\n'):'暂无资料'}
function modePrompt(mode){let base=`当前考研资料：\n${contextText()}\n\n学习进度：\n${data.progress||'空'}\n\n复盘：\n${data.review||'空'}\n\n补充要求：\n${aiNote.value.trim()||'无'}`;if(mode==='mindmap')return`${base}\n\n请输出：1. 3 行内总览；2. 一个 Mermaid mindmap 代码块，中心节点是“考研备考”；3. 不超过 5 条下一步行动。`;if(mode==='plan')return`${base}\n\n请输出本周学习建议，按优先级排序，尽量具体到可执行动作。`;return`${base}\n\n请输出复盘提纲，包含完成情况、问题、原因和修正动作。`}
async function runAI(mode){if(!ai.apiKey)return alert('请先保存 DeepSeek API Key');aiOut.value='正在请求 DeepSeek...';try{let res=await fetch(`${ai.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${ai.apiKey}`},body:JSON.stringify({model:ai.model,messages:[{role:'system',content:'你是考研资料整理助手，只输出简洁 Markdown。'},{role:'user',content:modePrompt(mode)}],stream:false})});let text=await res.text();if(!res.ok)throw new Error(text||res.statusText);let json=JSON.parse(text);aiOut.value=json.choices?.[0]?.message?.content||json.output_text||text;data.log.unshift(`${new Date().toLocaleString()}：AI 生成「${mode}」；下一步：人工校对后落到复习计划`);persist()}catch(err){aiOut.value=`请求失败：${err.message}`;alert('DeepSeek 请求失败')}}
function copyAI(){let t=aiOut.value.trim();if(!t)return alert('没有可复制的结果');navigator.clipboard.writeText(t).then(()=>alert('已复制')).catch(()=>alert('复制失败'))}
render();loadAI();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
